apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: miranovich-eks-dev-cluster
  region: us-east-1

nodeGroups:
  - name: node-group-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 80
  - name: node-group-2
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 80

apiVersion: v1
kind: Namespace

metadata:
  name: devops-monitor
